kafka-producer-endpoint:
  bootstrap.servers: 192.168.99.100:9092
  client.id: round18MiniProc
  key.serializer: org.apache.kafka.common.serialization.StringSerializer
  value.serializer: org.apache.kafka.common.serialization.StringSerializer


kafka-consumer-endpoint:
  bootstrap.servers: 192.168.99.100:9092
  client.id: round18MiniProc
  position: 0
  key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
  value.deserializer: org.apache.kafka.common.serialization.StringDeserializer
  group.id: test-consumer-group
